[build-system]
requires = ["setuptools>=80.9.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "repository-manager"
version = "1.1.4"
description = "Manage your git projects"
readme = "README.md"
authors = [{ name = "Audel Rouhi", email = "knucklessg1@gmail.com" }]
license = { text = "MIT" }
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: Public Domain",
    "Environment :: Console",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
]
requires-python = ">=3.8"
dependencies = [
    "fastmcp>=2.11.3",
]

[project.scripts]
repository-manager = "repository_manager.repository_manager:repository_manager"
repository-manager-mcp = "repository_manager.repository_manager_mcp:repository_manager_mcp"

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools]
include-package-data = true
package-data = { "repository_manager" = ["repository_manager"] }
