[build-system]
requires = ["setuptools>=80.9.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "repository-manager"
version = "1.2.17"
description = "Manage your git projects"
readme = "README.md"
authors = [{ name = "Audel Rouhi", email = "knucklessg1@gmail.com" }]
license = { text = "MIT" }
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: Public Domain",
    "Environment :: Console",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
]
requires-python = ">=3.10"
dependencies = [
    "fastmcp>=3.0.0b1",
]


[project.optional-dependencies]
mcp = [
    "fastmcp>=3.0.0b1",
    "eunomia-mcp>=0.3.10",
    "fastapi>=0.128.0",
    "beautifulsoup4>=4.14.3",
    "httpx>=0.28.1",
    "mem0-mcp-server>=0.0.1",
]

a2a = [
    "pydantic-ai-slim[fastmcp,openai,anthropic,google,huggingface,a2a,ag-ui,web]>=1.32.0",
    "pydantic-ai-skills",
    "fastapi>=0.128.0",
    "pre-commit>=4.5.1",
    "bump2version>=1.0.1",
    "mcp-run-python>=0.0.22",
    "mem0-mcp-server>=0.0.1",
]

gitlab = [
    "gitlab-api[all]>=25.14.9",
]

all = [
    "fastmcp>=3.0.0b1",
    "eunomia-mcp>=0.3.10",
    "pydantic-ai-slim[fastmcp,openai,anthropic,google,huggingface,a2a,ag-ui,web]>=1.32.0",
    "pydantic-ai-skills",
    "fastapi>=0.128.0",
    "gitlab-api[all]>=25.14.9",
    "pre-commit>=4.5.1",
    "bump2version>=1.0.1",
    "beautifulsoup4>=4.14.3",
    "httpx>=0.28.1",
    "mcp-run-python>=0.0.22",
    "mem0-mcp-server>=0.0.1",
]

[project.scripts]
repository-manager = "repository_manager.repository_manager:repository_manager"
repository-manager-mcp = "repository_manager.repository_manager_mcp:repository_manager_mcp"
repository-manager-agent = "repository_manager.repository_manager_agent:agent_server"

[tool.setuptools.package-data]
repository_manager = ["mcp_config.json", "skills/**", "repositories-list.txt"]

[tool.setuptools.packages.find]
where = ["."]
